### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by niladam** [r3volution11/material-palenight-alfred-theme#1]
Dude -- i just wanted to thank you. I just discovered this and i love it!

It looks amazing! If you could adapt this to Sublime Text, i'd love that too!

Obviously, you can close this!:)

Thank you for your work!

**Comment by r3volution11** [comment]
Thanks, @niladam. The Alfred theme is based on a theme that's already been created for Sublime Text. Check it out at https://github.com/equinusocio/material-theme.
